include:
  - project: eng/libadalang/libadalang
    file: /utils/gitlab-ci-common.yml
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/pre-commit@~latest
    inputs:
      stage: single
  - component: $CI_SERVER_FQDN/it/gitlab-templates/thirdparties-bundles@~latest
    inputs:
      prepare_deploy_stage: "deploy"
      deploy_stage: "deploy"
      job_with_bundle_generation_artifacts: "create_extension_lock_file"
      allow_audit_failure: "true"
      job_with_bundle_generation_artifacts_rules:
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
          when: manual
        # - if: '$CI_COMMIT_BRANCH != "master"'
        #   when: never
        # - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
        #   when: manual

stages:
  - single
  - vscode_ext
  - deploy


###############
# CHECK_ISSUE #
###############

check_issue:
  extends: .check_issue
  stage: single


##########################
# LANGKIT_BUILD_AND_TEST #
##########################

langkit_build_and_test:
  extends: .basic
  rules:
    # Run this for merge requests only
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  services:
     - image:pe-base
     - cpu:16
     - mem:16
  stage: single
  script:
    - generic_anod_ci
    - . /tmp/ci_env.sh
    - anod run
        --plan utils/gitlab-ci.plan
        --smart-rebuild
        run_ci

    # We must parse testsuite results with the same version of e3-testsuite
    # that produced them. So we install e3-testsuite using the same sandbox as
    # testing.
    - anod install e3-for-testing
    - eval $(anod printenv e3-for-testing)
    - testsuite_reports

    # Gather Cobertura report files
    - TEST_DIR=$(anod info test langkit -Qcoverage --show working_dir)
    - cp -r $TEST_DIR/results/new/lkt_coverage/cobertura coverage

    # Print metrics for integration in MR summary
    - print-global-coverage coverage/*.xml

    # Display the coverage summary in the job log for convenience
    - cat $TEST_DIR/results/new/comment
  artifacts:
    paths:
      - xunit-*.xml
      - coverage/*.xml
    reports:
      junit: xunit-*.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/*.xml
  coverage: '/^Line Coverage:\s+(\d+\.\d+)$/'


#############################
# LIBADALANG_BUILD_AND_TEST #
#############################

libadalang_build_and_test:
  extends: .basic
  services:
     - image:pe-base
     - cpu:16
     - mem:16
  stage: single
  rules:
    # Run this for merge requests only
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    # We frequently push coupled changes to Libadalang and Langkit: when this
    # happens, it is no longer possible to build Libadalang with Langkit's
    # master branch and Libadalang's nightly sources.  To solve this problem,
    # always pretend that we have Libadalang changes in the pipe (it would have
    # been rebuilt anyway).
    - generic_anod_ci --add-dep eng/libadalang/libadalang
    - . /tmp/ci_env.sh
    - anod test libadalang $ACI_TRACK_QUALIFIER --smart-rebuild

    # We must parse testsuite results with the same version of e3-testsuite
    # that produced them. So we install e3-testsuite using the same sandbox as
    # testing.
    - anod install e3-for-testing
    - eval $(anod printenv e3-for-testing)
    - testsuite_reports
  artifacts:
    reports:
      junit: xunit-*.xml


######
# CB #
######

continuous_builder:
  extends: .cb
  stage: single

##############################
# CREATE_EXTENSION_LOCK_FILE #
##############################

create_extension_lock_file:
  extends: .basic
  stage: vscode_ext
  needs: []
  services:
    - image:pe-base
    - cpu:16
    - mem:16
    - security_group:GitLabRunnerTasksExecPrivilegedSG
  script:
    - generic_anod_ci
    - . /tmp/ci_env.sh
    - anod build lkt-vscode-extension
    - BUILD_DIR=$(anod info build lkt-vscode-extension --show working_dir)/build
    - cp $BUILD_DIR/lkt_build/vscode_ext/package.json package.json
    - cp $BUILD_DIR/lkt_build/vscode_ext/package-lock.json package-lock.json
    - echo "BUNDLE_NAME=lkt-vscode-extension_npm-cache-$(date '+%Y%m%d')" >> variables.env
    - echo "PACKAGE_TYPE=node" >> variables.env
    - echo "PACKAGES_FILE=package.json" >> variables.env
  rules:
    # Run this on demand for merge requests only
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    # For security reasons, the Privileged security group is only granted to the
    # master branch. Considering we only want to create a new bundle when
    # updating the vscode extension dependencies, we make the job run manually.
    # - if: '$CI_COMMIT_BRANCH != "master"'
    #   when: never
    # - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web"'
    #   when: manual
  artifacts:
    reports:
      dotenv: variables.env
    paths:
      - package.json
      - package-lock.json
