env:
  global:
    # Directory to contain binary packages, sources and build trees for
    # dependencies (GNAT, GNATCOLL)
    - TOOLS_DIR=$HOME/build_tools

    # Prefix in which to install dependencies
    - INSTALL_DIR=$HOME/install

matrix:
  include:
    - os: linux
      language: python
      python: "2.7"

cache:
  directories:
  - $HOME/build_tools
  - $HOME/install
  - $HOME/.cache/pip
  timeout: 1000

install: utils/travis-install.sh
script:  utils/travis-script.sh
