env:
  global:
    # Directory to contain binary packages, sources and build trees for
    # dependencies (GNAT, GNATCOLL)
    - TOOLS_DIR=$HOME/build_tools

    # Prefix in which to install the toolchain
    - INSTALL_DIR=$HOME/install

    # Prefix in which to install dependencies. Avoid to install them in
    # $INSTALL_DIR, as they could confilct there with toolchain-provided
    # projects (which we want to override).
    - LIB_INSTALL_DIR=$HOME/lib-install

matrix:
  include:
    - os: linux
      language: python
      python: "3.7"

cache:
  directories:
  - $HOME/build_tools
  - $HOME/install
  - $HOME/.cache/pip
  timeout: 1000

install: utils/travis-install.sh
script:  utils/travis-script.sh
