## vim: filetype=makopython

def text_to_bytes(text: str) -> bytes: ...
def bytes_to_text(raw_bytes: bytes) -> str: ...
def unicode_character(char_code: int) -> str: ...
def text_repr(unistr: str) -> str: ...
def bytes_repr(bstr: bytes) -> str: ...
