const char lkt_builtin_file_90be36e7e1d5ea4b9b2ca8863caa55a4[] =
"{\n"
"  \"node_configs\": {\n"
"    \"AnyOf\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"field\": \"f_expr\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"in\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"contents\": {\n"
"              \"document\": {\n"
"                \"field\": \"f_values\",\n"
"                \"kind\": \"recurse_field\"\n"
"              },\n"
"              \"kind\": \"group\"\n"
"            },\n"
"            \"kind\": \"indent\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"AnyOfList\": {\n"
"      \"sep\": [\n"
"        \"line\",\n"
"        \"recurse\",\n"
"        \"whitespace\"\n"
"      ]\n"
"    },\n"
"    \"AnyTypePattern\": {},\n"
"    \"Argument\": {},\n"
"    \"ArgumentList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"ArrayLiteral\": {\n"
"      \"fields\": {\n"
"        \"f_element_type\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \":\"\n"
"          },\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ],\n"
"        \"f_exprs\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                {\n"
"                  \"document\": \"recurse\",\n"
"                  \"kind\": \"group\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"BaseCallExpr\": {\n"
"      \"fields\": {\n"
"        \"f_args\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": {\n"
"            \"document\": [\n"
"              {\n"
"                \"contents\": [\n"
"                  \"softline\",\n"
"                  \"recurse\"\n"
"                ],\n"
"                \"kind\": \"indent\"\n"
"              },\n"
"              \"softline\"\n"
"            ],\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"kind\": \"if\",\n"
"          \"then\": \"recurse\"\n"
"        },\n"
"        \"f_name\": {\n"
"          \"document\": {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_a\",\n"
"              \"kinds\": [\n"
"                \"DotExpr\",\n"
"                \"KeepExpr\",\n"
"                \"CastExpr\",\n"
"                \"CallExpr\"\n"
"              ],\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"recurse\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": \"recurse_flatten\"\n"
"          },\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      },\n"
"      \"node\": {\n"
"        \"document\": \"recurse\",\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"BaseImportList\": {},\n"
"    \"BaseLexerCaseRuleAlt\": {},\n"
"    \"BaseLexerCaseRuleAltList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"BaseMatchBranchList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"BigNumLit\": {},\n"
"    \"BinOp\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"field\": \"f_left\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"line\",\n"
"          {\n"
"            \"field\": \"f_op\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"field\": \"f_right\",\n"
"            \"kind\": \"recurse_field\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"BindingValDecl\": {},\n"
"    \"BlockExpr\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"contents\": [\n"
"            \"hardline\",\n"
"            {\n"
"              \"field\": \"f_clauses\",\n"
"              \"kind\": \"recurse_field\"\n"
"            }\n"
"          ],\n"
"          \"kind\": \"indent\"\n"
"        },\n"
"        \"hardline\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"BlockExprClause\": {},\n"
"    \"BlockStringLine\": {},\n"
"    \"BlockStringLineList\": {},\n"
"    \"BlockStringLit\": {},\n"
"    \"CallExprList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"CastExpr\": {\n"
"      \"fields\": {\n"
"        \"f_expr\": [\n"
"          {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_a\",\n"
"              \"kinds\": [\n"
"                \"DotExpr\",\n"
"                \"KeepExpr\",\n"
"                \"CastExpr\",\n"
"                \"CallExpr\"\n"
"              ],\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"recurse\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": \"recurse_flatten\"\n"
"          },\n"
"          \"softline\"\n"
"        ]\n"
"      },\n"
"      \"node\": {\n"
"        \"document\": \"recurse\",\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"CharLit\": {},\n"
"    \"ClassDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decls\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"hardline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"hardline\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ]\n"
"        },\n"
"        \"f_syn_base_type\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \":\"\n"
"          },\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ],\n"
"        \"f_traits\": [\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"implements\"\n"
"          },\n"
"          \"recurse\"\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"class\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_base_type\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_traits\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_decls\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"ClassQualifier\": {},\n"
"    \"ComplexPattern\": {\n"
"      \"fields\": {\n"
"        \"f_details\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": {\n"
"            \"document\": [\n"
"              {\n"
"                \"contents\": [\n"
"                  \"softline\",\n"
"                  \"recurse\"\n"
"                ],\n"
"                \"kind\": \"indent\"\n"
"              },\n"
"              \"softline\"\n"
"            ],\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"kind\": \"if\",\n"
"          \"then\": \"recurse\"\n"
"        },\n"
"        \"f_pattern\": {\n"
"          \"document\": {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_a\",\n"
"              \"kinds\": [\n"
"                \"OrPattern\"\n"
"              ],\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"recurse\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": \"recurse_flatten\"\n"
"          },\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"DeclAnnotation\": {\n"
"      \"node\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"DeclAnnotationArgs\": {\n"
"      \"fields\": {\n"
"        \"f_args\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                {\n"
"                  \"document\": \"recurse\",\n"
"                  \"kind\": \"group\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"DeclAnnotationList\": {},\n"
"    \"DefId\": {},\n"
"    \"DefaultListTypeRef\": {},\n"
"    \"DestructuringPatternDetail\": {\n"
"      \"node\": {\n"
"        \"field\": \"f_decl\",\n"
"        \"kind\": \"recurse_field\"\n"
"      }\n"
"    },\n"
"    \"DotExpr\": {\n"
"      \"fields\": {\n"
"        \"f_prefix\": [\n"
"          {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_a\",\n"
"              \"kinds\": [\n"
"                \"DotExpr\",\n"
"                \"KeepExpr\",\n"
"                \"CastExpr\",\n"
"                \"CallExpr\"\n"
"              ],\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"recurse\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": \"recurse_flatten\"\n"
"          },\n"
"          \"softline\"\n"
"        ]\n"
"      },\n"
"      \"node\": {\n"
"        \"document\": \"recurse\",\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"DynVarDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decl_type\": [\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"EllipsisPattern\": {},\n"
"    \"ElsifBranch\": {\n"
"      \"fields\": {\n"
"        \"f_cond_expr\": {\n"
"          \"default\": {\n"
"            \"document\": {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"kind\": \"match\",\n"
"          \"matchers\": [\n"
"            {\n"
"              \"document\": \"recurse\",\n"
"              \"kind\": [\n"
"                \"BlockExpr\",\n"
"                \"ParenExpr\"\n"
"              ]\n"
"            }\n"
"          ]\n"
"        },\n"
"        \"f_then_expr\": {\n"
"          \"default\": {\n"
"            \"document\": {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"kind\": \"match\",\n"
"          \"matchers\": [\n"
"            {\n"
"              \"document\": \"recurse\",\n"
"              \"kind\": [\n"
"                \"BlockExpr\",\n"
"                \"ParenExpr\"\n"
"              ]\n"
"            }\n"
"          ]\n"
"        }\n"
"      },\n"
"      \"node\": [\n"
"        \"hardline\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"elif\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_cond_expr\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"document\": [\n"
"            \"line\",\n"
"            {\n"
"              \"kind\": \"text\",\n"
"              \"text\": \"then\"\n"
"            },\n"
"            \"whitespace\",\n"
"            {\n"
"              \"field\": \"f_then_expr\",\n"
"              \"kind\": \"recurse_field\"\n"
"            }\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"ElsifBranchList\": {\n"
"      \"flush_before_children\": false\n"
"    },\n"
"    \"EnumClassAltDecl\": {},\n"
"    \"EnumClassAltDeclList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"EnumClassCase\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"case\"\n"
"        },\n"
"        {\n"
"          \"document\": {\n"
"            \"contents\": [\n"
"              \"line\",\n"
"              {\n"
"                \"field\": \"f_decls\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          },\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"EnumClassCaseList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"EnumClassDecl\": {\n"
"      \"fields\": {\n"
"        \"f_branches\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": \"recurse\"\n"
"        },\n"
"        \"f_decls\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": \"recurse\"\n"
"        },\n"
"        \"f_syn_base_type\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \":\"\n"
"          },\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"enum\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"class\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_base_type\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_traits\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"contents\": [\n"
"            {\n"
"              \"field\": \"f_branches\",\n"
"              \"kind\": \"recurse_field\"\n"
"            },\n"
"            {\n"
"              \"field\": \"f_decls\",\n"
"              \"kind\": \"recurse_field\"\n"
"            }\n"
"          ],\n"
"          \"kind\": \"indent\"\n"
"        },\n"
"        \"hardline\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"EnumLitDecl\": {},\n"
"    \"EnumLitDeclList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"EnumTypeDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decls\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": \"recurse\"\n"
"        }\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"enum\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_traits\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"contents\": [\n"
"            \"hardline\",\n"
"            {\n"
"              \"kind\": \"text\",\n"
"              \"text\": \"case\"\n"
"            },\n"
"            {\n"
"              \"document\": {\n"
"                \"contents\": [\n"
"                  \"line\",\n"
"                  {\n"
"                    \"field\": \"f_literals\",\n"
"                    \"kind\": \"recurse_field\"\n"
"                  }\n"
"                ],\n"
"                \"kind\": \"indent\"\n"
"              },\n"
"              \"kind\": \"group\"\n"
"            },\n"
"            {\n"
"              \"field\": \"f_decls\",\n"
"              \"kind\": \"recurse_field\"\n"
"            }\n"
"          ],\n"
"          \"kind\": \"indent\"\n"
"        },\n"
"        \"hardline\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"EnvSpecDecl\": {\n"
"      \"fields\": {\n"
"        \"f_actions\": [\n"
"          {\n"
"            \"contents\": [\n"
"              {\n"
"                \"condition\": {\n"
"                  \"kind\": \"is_empty\",\n"
"                  \"node\": \"this_field\"\n"
"                },\n"
"                \"else\": \"hardline\",\n"
"                \"kind\": \"if\",\n"
"                \"then\": []\n"
"              },\n"
"              \"recurse\"\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          },\n"
"          \"hardline\"\n"
"        ],\n"
"        \"f_syn_name\": [\n"
"          \"recurse\",\n"
"          \"whitespace\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"ErrorOnNull\": {},\n"
"    \"ExcludesNull\": {},\n"
"    \"ExprList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"FieldDecl\": {\n"
"      \"fields\": {\n"
"        \"f_default_val\": [\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"=\"\n"
"          },\n"
"          {\n"
"            \"default\": {\n"
"              \"document\": {\n"
"                \"contents\": [\n"
"                  \"line\",\n"
"                  \"recurse\"\n"
"                ],\n"
"                \"kind\": \"indent\"\n"
"              },\n"
"              \"kind\": \"group\"\n"
"            },\n"
"            \"kind\": \"match\",\n"
"            \"matchers\": [\n"
"              {\n"
"                \"document\": [\n"
"                  \"whitespace\",\n"
"                  \"recurse\"\n"
"                ],\n"
"                \"kind\": \"BlockExpr\"\n"
"              },\n"
"              {\n"
"                \"document\": [\n"
"                  \"whitespace\",\n"
"                  \"recurse\"\n"
"                ],\n"
"                \"kind\": \"ParenExpr\"\n"
"              }\n"
"            ]\n"
"          }\n"
"        ],\n"
"        \"f_trait_ref\": [\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \":\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_decl_type\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_trait_ref\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_default_val\",\n"
"          \"kind\": \"recurse_field\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"FieldPatternDetail\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"field\": \"f_id\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \":\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_expected_value\",\n"
"          \"kind\": \"recurse_field\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"FullDecl\": {},\n"
"    \"FullDeclList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"FunDecl\": {\n"
"      \"fields\": {\n"
"        \"f_body\": [\n"
"          \"whitespace\",\n"
"          {\n"
"            \"default\": {\n"
"              \"document\": {\n"
"                \"contents\": [\n"
"                  {\n"
"                    \"kind\": \"text\",\n"
"                    \"text\": \"=\"\n"
"                  },\n"
"                  \"line\",\n"
"                  \"recurse\"\n"
"                ],\n"
"                \"kind\": \"indent\"\n"
"              },\n"
"              \"kind\": \"group\"\n"
"            },\n"
"            \"kind\": \"match\",\n"
"            \"matchers\": [\n"
"              {\n"
"                \"document\": [\n"
"                  {\n"
"                    \"kind\": \"text\",\n"
"                    \"text\": \"=\"\n"
"                  },\n"
"                  \"whitespace\",\n"
"                  \"recurse\"\n"
"                ],\n"
"                \"kind\": [\n"
"                  \"BlockExpr\",\n"
"                  \"MatchExpr\"\n"
"                ]\n"
"              }\n"
"            ]\n"
"          }\n"
"        ],\n"
"        \"f_trait_ref\": [\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"implements\"\n"
"          },\n"
"          \"recurse\"\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"fun\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"(\"\n"
"        },\n"
"        {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                {\n"
"                  \"field\": \"f_params\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \")\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \":\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_return_type\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_trait_ref\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_body\",\n"
"          \"kind\": \"recurse_field\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"FunParamDecl\": {\n"
"      \"fields\": {\n"
"        \"f_default_val\": [\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"=\"\n"
"          },\n"
"          {\n"
"            \"document\": {\n"
"              \"contents\": [\n"
"                \"line\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"kind\": \"group\"\n"
"          }\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"field\": \"f_decl_annotations\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \":\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_decl_type\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_default_val\",\n"
"          \"kind\": \"recurse_field\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"FunParamDeclList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"FunctionTypeRef\": {},\n"
"    \"GenericDecl\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"generic\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"[\"\n"
"        },\n"
"        {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                {\n"
"                  \"field\": \"f_generic_param_decls\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"]\"\n"
"        },\n"
"        \"hardline\",\n"
"        {\n"
"          \"field\": \"f_decl\",\n"
"          \"kind\": \"recurse_field\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"GenericInstantiation\": {},\n"
"    \"GenericParamDeclList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"GenericParamTypeDecl\": {},\n"
"    \"GenericTypeRef\": {},\n"
"    \"GrammarCut\": {},\n"
"    \"GrammarDecl\": {\n"
"      \"fields\": {\n"
"        \"f_rules\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"hardline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"hardline\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ]\n"
"        }\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"grammar\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_rules\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"GrammarDiscard\": {\n"
"      \"fields\": {\n"
"        \"f_expr\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"GrammarDontSkip\": {},\n"
"    \"GrammarExprList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"GrammarExprListList\": {\n"
"      \"leading_sep\": [\n"
"        \"recurse\",\n"
"        \"whitespace\"\n"
"      ],\n"
"      \"sep\": [\n"
"        \"line\",\n"
"        \"recurse\",\n"
"        \"whitespace\"\n"
"      ]\n"
"    },\n"
"    \"GrammarImplicitPick\": {\n"
"      \"fields\": {\n"
"        \"f_exprs\": \"recurse\"\n"
"      }\n"
"    },\n"
"    \"GrammarList\": {\n"
"      \"fields\": {\n"
"        \"f_sep\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \",\"\n"
"          },\n"
"          \"line\",\n"
"          \"recurse\"\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"field\": \"f_list_type\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_kind\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"(\"\n"
"        },\n"
"        {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                {\n"
"                  \"field\": \"f_expr\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                },\n"
"                {\n"
"                  \"field\": \"f_sep\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \")\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"GrammarListSep\": {\n"
"      \"fields\": {\n"
"        \"f_extra\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \",\"\n"
"          },\n"
"          \"line\",\n"
"          \"recurse\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"GrammarNull\": {},\n"
"    \"GrammarOpt\": {},\n"
"    \"GrammarOptError\": {},\n"
"    \"GrammarOptErrorGroup\": {\n"
"      \"fields\": {\n"
"        \"f_expr\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"GrammarOptGroup\": {\n"
"      \"fields\": {\n"
"        \"f_expr\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"GrammarOrExpr\": {\n"
"      \"fields\": {\n"
"        \"f_sub_exprs\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"GrammarPick\": {\n"
"      \"fields\": {\n"
"        \"f_exprs\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"GrammarPredicate\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"field\": \"f_expr\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"|>\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"when\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"(\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_prop_ref\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \")\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"GrammarRuleDecl\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"<-\"\n"
"        },\n"
"        {\n"
"          \"default\": [\n"
"            \"whitespace\",\n"
"            {\n"
"              \"field\": \"f_expr\",\n"
"              \"kind\": \"recurse_field\"\n"
"            }\n"
"          ],\n"
"          \"field\": \"f_expr\",\n"
"          \"kind\": \"match\",\n"
"          \"matchers\": [\n"
"            {\n"
"              \"document\": {\n"
"                \"contents\": {\n"
"                  \"document\": [\n"
"                    \"line\",\n"
"                    {\n"
"                      \"field\": \"f_expr\",\n"
"                      \"kind\": \"recurse_field\"\n"
"                    }\n"
"                  ],\n"
"                  \"kind\": \"group\"\n"
"                },\n"
"                \"kind\": \"indent\"\n"
"              },\n"
"              \"kind\": [\n"
"                \"TokenLit\",\n"
"                \"TokenPatternLit\"\n"
"              ]\n"
"            }\n"
"          ]\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"GrammarRuleRef\": {},\n"
"    \"GrammarSkip\": {},\n"
"    \"GrammarStopCut\": {\n"
"      \"fields\": {\n"
"        \"f_expr\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"Id\": {},\n"
"    \"IfExpr\": {\n"
"      \"fields\": {\n"
"        \"f_cond_expr\": {\n"
"          \"default\": {\n"
"            \"document\": {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"kind\": \"match\",\n"
"          \"matchers\": [\n"
"            {\n"
"              \"document\": \"recurse\",\n"
"              \"kind\": [\n"
"                \"BlockExpr\",\n"
"                \"ParenExpr\"\n"
"              ]\n"
"            }\n"
"          ]\n"
"        },\n"
"        \"f_else_expr\": {\n"
"          \"default\": {\n"
"            \"document\": {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"kind\": \"match\",\n"
"          \"matchers\": [\n"
"            {\n"
"              \"document\": \"recurse\",\n"
"              \"kind\": [\n"
"                \"BlockExpr\",\n"
"                \"ParenExpr\"\n"
"              ]\n"
"            }\n"
"          ]\n"
"        },\n"
"        \"f_then_expr\": {\n"
"          \"default\": {\n"
"            \"document\": {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"kind\": \"match\",\n"
"          \"matchers\": [\n"
"            {\n"
"              \"document\": \"recurse\",\n"
"              \"kind\": [\n"
"                \"BlockExpr\",\n"
"                \"ParenExpr\"\n"
"              ]\n"
"            }\n"
"          ]\n"
"        }\n"
"      },\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"document\": [\n"
"              {\n"
"                \"kind\": \"text\",\n"
"                \"text\": \"if\"\n"
"              },\n"
"              \"whitespace\",\n"
"              {\n"
"                \"field\": \"f_cond_expr\",\n"
"                \"kind\": \"recurse_field\"\n"
"              },\n"
"              \"line\",\n"
"              {\n"
"                \"kind\": \"text\",\n"
"                \"text\": \"then\"\n"
"              },\n"
"              \"whitespace\",\n"
"              {\n"
"                \"field\": \"f_then_expr\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          {\n"
"            \"document\": {\n"
"              \"field\": \"f_alternatives\",\n"
"              \"kind\": \"recurse_field\"\n"
"            },\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"line\",\n"
"          {\n"
"            \"document\": [\n"
"              {\n"
"                \"kind\": \"text\",\n"
"                \"text\": \"else\"\n"
"              },\n"
"              \"whitespace\",\n"
"              {\n"
"                \"field\": \"f_else_expr\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"group\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"Import\": {\n"
"      \"node\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"ImportAllFrom\": {\n"
"      \"node\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"ImportFrom\": {\n"
"      \"node\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"ImportedId\": {},\n"
"    \"ImportedName\": {},\n"
"    \"ImportedNameList\": {},\n"
"    \"Isa\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"field\": \"f_expr\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"is\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"field\": \"f_pattern\",\n"
"            \"kind\": \"recurse_field\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"KeepExpr\": {\n"
"      \"fields\": {\n"
"        \"f_expr\": [\n"
"          {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_a\",\n"
"              \"kinds\": [\n"
"                \"DotExpr\",\n"
"                \"KeepExpr\",\n"
"                \"CastExpr\",\n"
"                \"CallExpr\"\n"
"              ],\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"recurse\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": \"recurse_flatten\"\n"
"          },\n"
"          \"softline\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"LambdaExpr\": {\n"
"      \"fields\": {\n"
"        \"f_params\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        },\n"
"        \"f_return_type\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \":\"\n"
"          },\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"(\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_params\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \")\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_return_type\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"bubbleUpTrailingTrivias\": false,\n"
"          \"document\": [\n"
"            {\n"
"              \"kind\": \"text\",\n"
"              \"text\": \"=>\"\n"
"            },\n"
"            \"flushLineBreaks\"\n"
"          ],\n"
"          \"id\": \"comments\",\n"
"          \"kind\": \"group\"\n"
"        },\n"
"        {\n"
"          \"default\": {\n"
"            \"document\": [\n"
"              {\n"
"                \"breakContents\": [],\n"
"                \"flatContents\": \"line\",\n"
"                \"groupId\": \"comments\",\n"
"                \"kind\": \"ifBreak\"\n"
"              },\n"
"              {\n"
"                \"field\": \"f_body\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          \"field\": \"f_body\",\n"
"          \"kind\": \"match\",\n"
"          \"matchers\": [\n"
"            {\n"
"              \"document\": [\n"
"                {\n"
"                  \"breakContents\": [],\n"
"                  \"flatContents\": \"whitespace\",\n"
"                  \"groupId\": \"comments\",\n"
"                  \"kind\": \"ifBreak\"\n"
"                },\n"
"                {\n"
"                  \"field\": \"f_body\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"BlockExpr\"\n"
"            }\n"
"          ]\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"LambdaParamDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decl_type\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \":\"\n"
"          },\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ],\n"
"        \"f_default_val\": [\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"=\"\n"
"          },\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"LambdaParamDeclList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"LangkitRoot\": {\n"
"      \"fields\": {\n"
"        \"f_imports\": [\n"
"          \"recurse\",\n"
"          {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_empty\",\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"hardline\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": []\n"
"          }\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"LexerCaseRule\": {\n"
"      \"fields\": {\n"
"        \"f_alts\": [\n"
"          {\n"
"            \"contents\": [\n"
"              \"hardline\",\n"
"              \"recurse\"\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          },\n"
"          \"hardline\"\n"
"        ]\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"match\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_expr\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_alts\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"LexerCaseRuleSend\": {\n"
"      \"fields\": {\n"
"        \"f_match_size\": [\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"LexerDecl\": {\n"
"      \"fields\": {\n"
"        \"f_rules\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"hardline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"hardline\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ]\n"
"        }\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"lexer\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_rules\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"LexerFamilyDecl\": {\n"
"      \"fields\": {\n"
"        \"f_rules\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"hardline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"hardline\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ]\n"
"        }\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"family\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_rules\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"ListKind\": {},\n"
"    \"LktNodeList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"hardline\"\n"
"      ]\n"
"    },\n"
"    \"LogicAssign\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"field\": \"f_dest_var\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"line\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"<-\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"field\": \"f_value\",\n"
"            \"kind\": \"recurse_field\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"LogicExpr\": {},\n"
"    \"LogicPredicate\": {},\n"
"    \"LogicPropagate\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"field\": \"f_dest_var\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"line\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"<-\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"field\": \"f_call\",\n"
"            \"kind\": \"recurse_field\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"LogicUnify\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"field\": \"f_lhs\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"line\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"<->\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"field\": \"f_rhs\",\n"
"            \"kind\": \"recurse_field\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"MatchBranch\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"case\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_decl\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"=>\"\n"
"        },\n"
"        {\n"
"          \"document\": {\n"
"            \"contents\": [\n"
"              \"line\",\n"
"              {\n"
"                \"field\": \"f_expr\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          },\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"MatchExpr\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"match\"\n"
"        },\n"
"        {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"line\",\n"
"                {\n"
"                  \"field\": \"f_match_expr\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"line\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"contents\": [\n"
"            \"hardline\",\n"
"            {\n"
"              \"field\": \"f_branches\",\n"
"              \"kind\": \"recurse_field\"\n"
"            }\n"
"          ],\n"
"          \"kind\": \"indent\"\n"
"        },\n"
"        \"hardline\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"MatchValDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decl_type\": [\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"ModuleDocStringLine\": {},\n"
"    \"ModuleDocStringLineList\": {},\n"
"    \"ModuleDocStringLit\": {},\n"
"    \"ModuleId\": {},\n"
"    \"NotExpr\": {\n"
"      \"fields\": {\n"
"        \"f_expr\": {\n"
"          \"document\": [\n"
"            \"whitespace\",\n"
"            \"recurse\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"NotPattern\": {},\n"
"    \"NullCondQualifier\": {},\n"
"    \"NullLit\": {},\n"
"    \"NullPattern\": {},\n"
"    \"NumLit\": {},\n"
"    \"Op\": {},\n"
"    \"OrPattern\": {\n"
"      \"fields\": {\n"
"        \"f_left_sub_pattern\": [\n"
"          {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_a\",\n"
"              \"kinds\": [\n"
"                \"OrPattern\"\n"
"              ],\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"recurse\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": \"recurse_flatten\"\n"
"          },\n"
"          \"line\"\n"
"        ],\n"
"        \"f_right_sub_pattern\": [\n"
"          \"whitespace\",\n"
"          {\n"
"            \"condition\": {\n"
"              \"kind\": \"is_a\",\n"
"              \"kinds\": [\n"
"                \"OrPattern\"\n"
"              ],\n"
"              \"node\": \"this_field\"\n"
"            },\n"
"            \"else\": \"recurse\",\n"
"            \"kind\": \"if\",\n"
"            \"then\": \"recurse_flatten\"\n"
"          }\n"
"        ]\n"
"      },\n"
"      \"node\": {\n"
"        \"document\": \"recurse\",\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"ParenExpr\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"contents\": [\n"
"              {\n"
"                \"kind\": \"text\",\n"
"                \"text\": \"(\"\n"
"              },\n"
"              \"softline\",\n"
"              {\n"
"                \"document\": {\n"
"                  \"field\": \"f_expr\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                },\n"
"                \"kind\": \"group\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          },\n"
"          \"softline\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \")\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"ParenPattern\": {},\n"
"    \"ParseNodeExpr\": {\n"
"      \"fields\": {\n"
"        \"f_sub_exprs\": {\n"
"          \"document\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"softline\",\n"
"                {\n"
"                  \"document\": \"recurse\",\n"
"                  \"kind\": \"group\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"softline\"\n"
"          ],\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      }\n"
"    },\n"
"    \"Pattern\": {},\n"
"    \"PatternDetailList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"line\"\n"
"      ]\n"
"    },\n"
"    \"PatternList\": {},\n"
"    \"PatternMatchBranch\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"case\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_pattern\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"=>\"\n"
"        },\n"
"        {\n"
"          \"document\": {\n"
"            \"contents\": [\n"
"              \"line\",\n"
"              {\n"
"                \"field\": \"f_expr\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          },\n"
"          \"kind\": \"group\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"PropertyPatternDetail\": {\n"
"      \"node\": [\n"
"        {\n"
"          \"field\": \"f_call\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \":\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_expected_value\",\n"
"          \"kind\": \"recurse_field\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"Query\": {},\n"
"    \"RaiseExpr\": {\n"
"      \"fields\": {\n"
"        \"f_except_expr\": [\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      }\n"
"    },\n"
"    \"RefId\": {},\n"
"    \"RefIdList\": {},\n"
"    \"RegexPattern\": {},\n"
"    \"SimpleTypeRef\": {},\n"
"    \"SingleLineStringLit\": {},\n"
"    \"StructDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decls\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"hardline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"hardline\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ]\n"
"        }\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"struct\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_traits\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_decls\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"SubscriptExpr\": {\n"
"      \"fields\": {\n"
"        \"f_index\": [\n"
"          {\n"
"            \"contents\": [\n"
"              \"softline\",\n"
"              \"recurse\"\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          },\n"
"          \"softline\"\n"
"        ]\n"
"      },\n"
"      \"node\": {\n"
"        \"document\": \"recurse\",\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"TokenLit\": {},\n"
"    \"TokenNoCaseLit\": {},\n"
"    \"TokenPatternConcat\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"field\": \"f_left\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"line\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"&\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"field\": \"f_right\",\n"
"            \"kind\": \"recurse_field\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"TokenPatternLit\": {},\n"
"    \"TokenRef\": {},\n"
"    \"TraitDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decls\": {\n"
"          \"condition\": {\n"
"            \"kind\": \"is_empty\",\n"
"            \"node\": \"this_field\"\n"
"          },\n"
"          \"else\": [\n"
"            {\n"
"              \"contents\": [\n"
"                \"hardline\",\n"
"                \"recurse\"\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"hardline\"\n"
"          ],\n"
"          \"kind\": \"if\",\n"
"          \"then\": [\n"
"            \"hardline\",\n"
"            \"recurse\"\n"
"          ]\n"
"        }\n"
"      },\n"
"      \"node\": [\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"trait\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_syn_name\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        \"whitespace\",\n"
"        {\n"
"          \"field\": \"f_traits\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"{\"\n"
"        },\n"
"        {\n"
"          \"field\": \"f_decls\",\n"
"          \"kind\": \"recurse_field\"\n"
"        },\n"
"        {\n"
"          \"kind\": \"text\",\n"
"          \"text\": \"}\"\n"
"        }\n"
"      ]\n"
"    },\n"
"    \"TryExpr\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"document\": [\n"
"              {\n"
"                \"kind\": \"text\",\n"
"                \"text\": \"try\"\n"
"              },\n"
"              \"whitespace\",\n"
"              {\n"
"                \"field\": \"f_try_expr\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"group\"\n"
"          },\n"
"          {\n"
"            \"absent\": {\n"
"              \"field\": \"f_or_expr\",\n"
"              \"kind\": \"recurse_field\"\n"
"            },\n"
"            \"default\": [\n"
"              \"line\",\n"
"              {\n"
"                \"document\": {\n"
"                  \"field\": \"f_or_expr\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                },\n"
"                \"kind\": \"group\"\n"
"              }\n"
"            ],\n"
"            \"field\": \"f_or_expr\",\n"
"            \"kind\": \"match\",\n"
"            \"matchers\": []\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"TypePattern\": {},\n"
"    \"TypeRefList\": {\n"
"      \"sep\": [\n"
"        \"recurse\",\n"
"        \"whitespace\"\n"
"      ]\n"
"    },\n"
"    \"UnOp\": {},\n"
"    \"ValDecl\": {\n"
"      \"fields\": {\n"
"        \"f_decl_type\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \":\"\n"
"          },\n"
"          \"whitespace\",\n"
"          \"recurse\"\n"
"        ]\n"
"      },\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"val\"\n"
"          },\n"
"          {\n"
"            \"field\": \"f_syn_name\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          {\n"
"            \"field\": \"f_decl_type\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"=\"\n"
"          },\n"
"          {\n"
"            \"default\": {\n"
"              \"contents\": [\n"
"                \"line\",\n"
"                {\n"
"                  \"field\": \"f_expr\",\n"
"                  \"kind\": \"recurse_field\"\n"
"                }\n"
"              ],\n"
"              \"kind\": \"indent\"\n"
"            },\n"
"            \"field\": \"f_expr\",\n"
"            \"kind\": \"match\",\n"
"            \"matchers\": [\n"
"              {\n"
"                \"document\": [\n"
"                  \"whitespace\",\n"
"                  {\n"
"                    \"field\": \"f_expr\",\n"
"                    \"kind\": \"recurse_field\"\n"
"                  }\n"
"                ],\n"
"                \"kind\": [\n"
"                  \"BlockExpr\",\n"
"                  \"ParenExpr\",\n"
"                  \"MatchExpr\"\n"
"                ]\n"
"              }\n"
"            ]\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    },\n"
"    \"VarBind\": {\n"
"      \"node\": {\n"
"        \"document\": [\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"bind\"\n"
"          },\n"
"          {\n"
"            \"field\": \"f_name\",\n"
"            \"kind\": \"recurse_field\"\n"
"          },\n"
"          \"whitespace\",\n"
"          {\n"
"            \"kind\": \"text\",\n"
"            \"text\": \"=\"\n"
"          },\n"
"          {\n"
"            \"contents\": [\n"
"              \"line\",\n"
"              {\n"
"                \"field\": \"f_expr\",\n"
"                \"kind\": \"recurse_field\"\n"
"              }\n"
"            ],\n"
"            \"kind\": \"indent\"\n"
"          }\n"
"        ],\n"
"        \"kind\": \"group\"\n"
"      }\n"
"    }\n"
"  }\n"
"}\n"
"";
