on:
  push:
    branches:
      - master
      - stable
      - topic/ghactions
  pull_request:
    branches:
      - master
name: Linux CI
jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux build & test
    env:
      PROCESSORS: 0
      PREFIX: "/tmp/ADALIB_DIR"
      GPR_PROJECT_PATH: /tmp/ADALIB_DIR/share/gpr
    steps:
      - name: Get langkit
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install python dependencies
        run: |
            pip install -r REQUIREMENTS.dev
            pip install jsonschema
            pip install mypy==0.780
            python setup.py install
            pip install flake8

      - name: Get gprbuild for libgpr
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gprbuild
          path: gprbuild

      - name: Get gnatcoll core
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gnatcoll-core
          path: gnatcoll-core

      - name: Get gnatcoll iconv/gmp
        uses: actions/checkout@v2
        with:
          repository: AdaCore/gnatcoll-bindings
          path: gnatcoll-bindings

      - uses: actions/cache@v2
        with:
          path: ./cached_gnat
          key: ${{ runner.os }}-gnat-ce-2020
      - name: Get GNAT Community 2020 toolchain
        uses: ada-actions/toolchain@3f69585
        with:
          distrib: community
          install_dir: ./cached_gnat

      - name: Cache build artifacts
        uses: actions/cache@v2
        id: cache
        with:
          path: |
              gprbuild/gpr/libobj
              gnatcoll-core/obj
              gnatcoll-bindings/gmp/obj
              gnatcoll-bindings/iconv/obj
              contrib/python/build/obj
              contrib/lkt/build/obj
          key: ${{ runner.os }}-build-artifacts-2

      - name: Build dependencies
        run: |
            make -C gprbuild prefix=$PREFIX GPRBUILD_OPTIONS="-cargs:C -Dst_mtim=st_mtimespec -gargs" libgpr.build libgpr.install
            make -C gnatcoll-core prefix=$PREFIX ENABLE_SHARED=yes build install
            python gnatcoll-bindings/iconv/setup.py build -j0 --prefix=$PREFIX --library-types=static,relocatable
            python gnatcoll-bindings/iconv/setup.py install
            python gnatcoll-bindings/gmp/setup.py build ${DEBUG:+--debug} -j0 --prefix=$PREFIX --library-types=static,relocatable
            python gnatcoll-bindings/gmp/setup.py install

      - name: Build
        run: |
            set -x -e
            utils/gh_wrap_errors.py ./manage.py make

      - name: Run mypy checks
        run: |
            eval `./manage.py setenv`
            python utils/gh_wrap_errors.py mypy --config-file=mypy.ini

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Test
        run: |
            set -x -e
            eval `./manage.py setenv`
            ./manage.py test --no-auto-path --disable-ocaml --failure-exit-code=1
